import os
import glob
import frontmatter
from datetime import datetime, timezone

PROJECTS_DIR = 'projects'
DASHBOARD_FILE = 'DASHBOARD.md'

def generate_dashboard():
    dashboard_content = [
        "<!-- This file is AUTO-GENERATED by scripts/aggregator.py. DO NOT EDIT MANUALLY. -->",
        "# 📈 Executive Project Dashboard",
        f"*Last Updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC*\n",
        "## Active Projects Overview",
        "| Project | Status | Next Steps | Owner |",
        "| :--- | :--- | :--- | :--- |"
    ]

    # Crawl the projects directory for all markdown files
    search_pattern = os.path.join(PROJECTS_DIR, '**', '*.md')
    md_files = glob.glob(search_pattern, recursive=True)

    for filepath in md_files:
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                post = frontmatter.load(f)
                
            # Only process files that have our specific PMaC metadata
            if all(key in post.keys() for key in ['project_name', 'status', 'next_steps']):
                name = post['project_name']
                status = post['status']
                steps = post['next_steps']
                owner = post.get('owner', 'Unassigned')
                
                # Apply color-coding to status
                status_indicator = status
                if status.lower() == 'green':
                    status_indicator = '🟢 Green'
                elif status.lower() == 'yellow':
                    status_indicator = '🟡 Yellow'
                elif status.lower() == 'red':
                    status_indicator = '🔴 Red'

                dashboard_content.append(f"| **{name}** | {status_indicator} | {steps} | {owner} |")
        except Exception as e:
            print(f"Error parsing {filepath}: {e}")

    # Write the compiled dashboard
    with open(DASHBOARD_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(dashboard_content))
        f.write('\n')

    print(f"Successfully generated {DASHBOARD_FILE}")

if __name__ == "__main__":
    generate_dashboard()